<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Project Request</name>
   <tag></tag>
   <elementGuidId>74888850-b579-4908-bb78-2260f72d6960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div[2]/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fd4d323-02db-4061-b076-d076bf19edee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project-request</value>
      <webElementGuid>47358b1d-2566-4abf-9a69-76bce2cab281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-4 px-3 py-1 text-sm font-medium text-blk-light focus:outline-none</value>
      <webElementGuid>b6c05072-d3bc-4532-beb7-965770a7125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project Request</value>
      <webElementGuid>fbc0c83d-f00c-4653-9261-d18f71caebbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[1]/div[@class=&quot;bg-white pt-5&quot;]/div[@class=&quot;container mx-auto uppercase flex justify-center py-1&quot;]/a[@class=&quot;ml-4 px-3 py-1 text-sm font-medium text-blk-light focus:outline-none&quot;]</value>
      <webElementGuid>b5b066af-2fc4-4262-9423-dabc5594daaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/a[3]</value>
      <webElementGuid>5d1ae647-2760-45c2-a72e-8de2c80ae9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Project Request')]</value>
      <webElementGuid>e0f29e4f-5a53-49ac-a38a-721ea03eaa28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Data'])[1]/following::a[1]</value>
      <webElementGuid>75da9893-59d0-4386-a982-5e2615fd7c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>c1f45ae8-3d12-4f1a-856d-9578aaa1df43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design &amp; Development'])[1]/preceding::a[1]</value>
      <webElementGuid>1d0eb4ef-0a24-4286-ad36-e4c71e4ee04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tender'])[1]/preceding::a[2]</value>
      <webElementGuid>ca30ddd6-7221-4164-affd-022c78ef75fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Project Request']/parent::*</value>
      <webElementGuid>943c2829-a522-497c-a9c3-d703bc052a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/project-request')]</value>
      <webElementGuid>02a4c7b8-e59e-45ef-b09b-2b77af3485f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>2637eaf9-f468-4580-bd1b-c8fbc1a6424d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/project-request' and (text() = 'Project Request' or . = 'Project Request')]</value>
      <webElementGuid>638627ad-74e9-47a6-978d-fdce68b1ecbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
