<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Propose</name>
   <tag></tag>
   <elementGuidId>fe97a7ba-ecb4-4d50-8dbf-0ece5f5ef4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[9]/div[2]/div/div[2]/div/table/tr[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e10405f9-c7b1-4dfe-aa4f-cc813ea139d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 whitespace-nowrap hover:bg-blue hover:text-white text-sm cursor-pointer</value>
      <webElementGuid>dce966b9-7bab-4803-9374-7d7958ef765a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Propose
                      </value>
      <webElementGuid>04765b48-d6cb-4916-a9bb-a84632995e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[2]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;px-4 h-screen&quot;]/div[@class=&quot;flex flex-col mt-5&quot;]/div[@class=&quot;-my-2 sm:-mx-6 lg:-mx-8&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8&quot;]/div[@class=&quot;shadow border-b border-gray-200 sm:rounded-lg&quot;]/div[1]/table[@class=&quot;min-w-full divide-y divide-gray-200&quot;]/tbody[@class=&quot;bg-white divide-y divide-gray-200&quot;]/tr[2]/td[@class=&quot;px-4 py-4 whitespace-wrap&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;top-2.5 absolute block&quot;]/div[@class=&quot;bg-gry z-50 origin-top-right absolute right-0 w-35 rounded border-gry border-2 -mt-2.5&quot;]/table[@class=&quot;divide-y divide-gray-200 text-blue bg-white shadow&quot;]/tr[3]/div[@class=&quot;px-4 py-2 whitespace-nowrap hover:bg-blue hover:text-white text-sm cursor-pointer&quot;]</value>
      <webElementGuid>aa346d0e-0cfc-4a3d-aad1-5a7e67d51727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[9]/div[2]/div/div[2]/div/table/tr[3]/div</value>
      <webElementGuid>da1427ca-542e-4b6e-9af0-a897231497f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::div[1]</value>
      <webElementGuid>b017e2d6-d4cd-4140-9248-1bca63256452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[2]/following::div[2]</value>
      <webElementGuid>baeb8518-7966-4848-9197-fec4b13ee1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select PIC'])[2]/preceding::div[1]</value>
      <webElementGuid>708fdb68-b90b-4d8d-8c72-9bf84914c624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Project'])[2]/preceding::div[2]</value>
      <webElementGuid>d5be62ab-2397-4ff2-b6f9-ef6531f19133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tr[3]/div</value>
      <webElementGuid>bc987501-0214-4dc0-a161-85e48d393a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        Propose
                      ' or . = '
                        Propose
                      ')]</value>
      <webElementGuid>ca3a9235-5d61-41bf-a2d9-fef88af02aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
