<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_-_fas fa-ellipsis-v cursor-pointer</name>
   <tag></tag>
   <elementGuidId>7186929f-e541-49eb-88f7-babdfec7ee8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[9]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ff64cf3f-fac7-4594-ba9f-dbd806af15d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-ellipsis-v cursor-pointer</value>
      <webElementGuid>77a93f74-becd-4745-ae87-035c59dff095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[2]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;px-4 h-screen&quot;]/div[@class=&quot;flex flex-col mt-5&quot;]/div[@class=&quot;-my-2 sm:-mx-6 lg:-mx-8&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8&quot;]/div[@class=&quot;shadow border-b border-gray-200 sm:rounded-lg&quot;]/div[1]/table[@class=&quot;min-w-full divide-y divide-gray-200&quot;]/tbody[@class=&quot;bg-white divide-y divide-gray-200&quot;]/tr[2]/td[@class=&quot;px-4 py-4 whitespace-wrap&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;flex flex-col&quot;]/i[@class=&quot;fas fa-ellipsis-v cursor-pointer&quot;]</value>
      <webElementGuid>a5897605-a7ac-47b0-936b-f10f85c9b958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[9]/div[2]/div/i</value>
      <webElementGuid>573e4a47-65c7-4417-a44d-361feae201fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/div[2]/div/i</value>
      <webElementGuid>f655d8b4-5fee-4562-9582-0080f9356c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
