<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_HNP_fas fa-ellipsis-v cursor-pointer</name>
   <tag></tag>
   <elementGuidId>b15a9409-bd96-42cb-94f5-6653c2685cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[3]/td[9]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7dcfe2d0-98df-421f-a594-3d6cbbda241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-ellipsis-v cursor-pointer</value>
      <webElementGuid>dc3c069d-62aa-4015-b686-0ad9be52000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[2]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;px-4 h-screen&quot;]/div[@class=&quot;flex flex-col mt-5&quot;]/div[@class=&quot;-my-2 sm:-mx-6 lg:-mx-8&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8&quot;]/div[@class=&quot;shadow border-b border-gray-200 sm:rounded-lg&quot;]/div[1]/table[@class=&quot;min-w-full divide-y divide-gray-200&quot;]/tbody[@class=&quot;bg-white divide-y divide-gray-200&quot;]/tr[3]/td[@class=&quot;px-4 py-4 whitespace-wrap&quot;]/div[@class=&quot;relative inline-block w-full&quot;]/div[@class=&quot;flex flex-col&quot;]/i[@class=&quot;fas fa-ellipsis-v cursor-pointer&quot;]</value>
      <webElementGuid>284c0ec6-c1b6-414f-b087-7d9fef7d9a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[3]/td[9]/div[2]/div/i</value>
      <webElementGuid>11e91f5c-0ae4-4fd3-8962-a680fd5f5977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/div[2]/div/i</value>
      <webElementGuid>50e8b535-acf6-4502-b186-85e4733d569e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
