<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Head OfficeBalikpapanJakartaLombok O_aafa85</name>
   <tag></tag>
   <elementGuidId>3ec402ce-f976-47b9-955b-82db96da3b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.input-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39d327fb-3625-4928-b7f2-16b04c05d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-select</value>
      <webElementGuid>47456a5b-1d10-41c9-b9df-430cc6b42ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Head OfficeBalikpapanJakartaLombok OfficeMalangmondaytester juaraCOBAPapuaSangataMalangZimbabwe</value>
      <webElementGuid>d8523c03-252f-4cd7-93de-77fbe0beee24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[2]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;mt-5&quot;]/div[1]/div[@class=&quot;w-full bg-white rounded-b-lg border-t-2 border-ylw&quot;]/div[@class=&quot;p-6&quot;]/div[1]/div[@class=&quot;flex flex-row gap-8&quot;]/div[@class=&quot;w-1/2&quot;]/div[@class=&quot;mt-3&quot;]/div[@class=&quot;relative h-10&quot;]/select[@class=&quot;input-select&quot;]</value>
      <webElementGuid>3b507cdb-06db-42b1-8b45-ba88eb4e3eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>2b224cf6-4c53-4226-b300-7d6563d2f9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area'])[1]/following::select[1]</value>
      <webElementGuid>04145908-7b32-4e47-afb8-c3f5314a36ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feasibility Study'])[1]/following::select[1]</value>
      <webElementGuid>8484083e-4c94-4d68-8475-f7b19d2fd93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Name'])[1]/preceding::select[1]</value>
      <webElementGuid>198939c9-965e-4494-90e1-74d85d600884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Status'])[1]/preceding::select[1]</value>
      <webElementGuid>9e07095b-89ad-4003-85ba-8da6844e0466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0e3f2719-3ae4-484f-b615-96bd567caebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Head OfficeBalikpapanJakartaLombok OfficeMalangmondaytester juaraCOBAPapuaSangataMalangZimbabwe' or . = 'Head OfficeBalikpapanJakartaLombok OfficeMalangmondaytester juaraCOBAPapuaSangataMalangZimbabwe')]</value>
      <webElementGuid>fbbe823d-fac1-4cba-8ac4-a71f3111f8dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
