<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Action_p-3</name>
   <tag></tag>
   <elementGuidId>bdeda13c-7f2b-4fbb-b25e-d77c0da74caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6603d3a6-405c-429c-b878-800c862c00ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3</value>
      <webElementGuid>41be7c22-6286-4701-a06e-d6177812d12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;font-mont bg-gry-light min-h-screen&quot;]/div[2]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;px-4 h-screen&quot;]/div[@class=&quot;flex flex-col mt-5&quot;]/div[@class=&quot;-my-2 sm:-mx-6 lg:-mx-8&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8&quot;]/div[@class=&quot;shadow border-b border-gray-200 sm:rounded-lg&quot;]/div[1]/table[@class=&quot;min-w-full divide-y divide-gray-200&quot;]/tbody[@class=&quot;bg-white divide-y divide-gray-200&quot;]/tr[2]/td[@class=&quot;p-3&quot;]</value>
      <webElementGuid>86a82102-e11c-4a33-bce1-c3bc508b6aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[5]</value>
      <webElementGuid>7d5164d3-09e9-414c-b1af-1ccfdf619705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[14]</value>
      <webElementGuid>2c36a478-45c3-4894-a1a7-613fa4e96638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Proposed'])[1]/following::td[14]</value>
      <webElementGuid>9a640120-f474-417f-9d81-83d56dc1185a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perpage'])[1]/preceding::td[32]</value>
      <webElementGuid>5eec7541-5bca-429e-b2e1-784214b11e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]</value>
      <webElementGuid>e9f44d16-fdb2-4853-b3c7-85165c344b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
